### ISSUE TITLE
History page

### ISSUE THREAD

**Issue by nzola** [ascoderu/ascoderu.github.io#14]
Hi Laura,
On history page of the website it is not clear that there is more detailed info beyond what are written there. Is there a way of indicating at the end of those summaries "Click for more"
Because now the word "more" comes up only when the mouse pointer is placed on the summary.

Thanks,
Nzola

**Comment by c-w** [comment]
@laura-barluzzi

**Comment by c-w** [comment]
![image](https://user-images.githubusercontent.com/1086421/40630511-2432adb8-62a1-11e8-9dbc-1af90d863fcf.png)
