### ISSUE TITLE
adding SSL certificate to the site

### ISSUE THREAD

**Issue by LeGrandMAG** [ascoderu/ascoderu.github.io#25]
It would be  great if the site had a SSL certificate. 

I would be glad to work on that

**Comment by c-w** [comment]
This used to work via the GitHub Pages free cert. Unsure what changed. I reckon DNS may have to be updated.

**Comment by LeGrandMAG** [comment]
I know that this can be easily fixed by enforcing the HTTPS on the github pages setting.

You can check more on this  [here](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https)

**Comment by c-w** [comment]
https://ascoderu.ca/ is back online; I also documented the steps for fixing the issue.
